server:
  port: 8031
spring:
  application:
    name: spring-cloud-turbine
eureka:
  client:
    service-url:
        defaultZone : http://root:root@discovery:8761/eureka/,http://root:root@discovery2:8762/eureka
  instance:
    prefer-ip-address: true
turbine:
  app-config: cia-j
  cluster-name-expression: "default"